; Lossless Toolbox installer - generated by .github/workflows/build-windows.yml
; Produced with makensis on the GitHub Actions windows-latest runner.
!define APP_NAME "Lossless Toolbox"
!define APP_VERSION "0.1.0"
!define APP_EXE "lossless-toolbox.exe"
!define UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\LosslessToolbox"

Name "${APP_NAME} ${APP_VERSION}"
OutFile "${OUTFILE}"
Unicode True
InstallDir "$PROGRAMFILES64\Lossless Toolbox"
InstallDirRegKey HKCU "${UNINST_KEY}" "InstallDir"
RequestExecutionLevel user

Page directory
Page instfiles
UninstPage uninstConfirm
UninstPage instfiles

Section "Install"
  SetOutPath "$INSTDIR"
  File /r "${SRCDIR}\*"
  WriteUninstaller "$INSTDIR\uninstall.exe"
  CreateDirectory "$SMPROGRAMS\Lossless Toolbox"
  CreateShortcut "$SMPROGRAMS\Lossless Toolbox\Lossless Toolbox.lnk" "$INSTDIR\${APP_EXE}"
  WriteRegStr HKCU "${UNINST_KEY}" "DisplayName" "${APP_NAME}"
  WriteRegStr HKCU "${UNINST_KEY}" "DisplayVersion" "${APP_VERSION}"
  WriteRegStr HKCU "${UNINST_KEY}" "Publisher" "Lossless Toolbox"
  WriteRegStr HKCU "${UNINST_KEY}" "InstallDir" "$INSTDIR"
  WriteRegStr HKCU "${UNINST_KEY}" "UninstallString" '"$INSTDIR\uninstall.exe"'
SectionEnd

Section "Uninstall"
  Delete "$INSTDIR\uninstall.exe"
  Delete "$SMPROGRAMS\Lossless Toolbox\Lossless Toolbox.lnk"
  RMDir "$SMPROGRAMS\Lossless Toolbox"
  RMDir /r "$INSTDIR"
  DeleteRegKey HKCU "${UNINST_KEY}"
SectionEnd
