"""Tests for the synthetic media factory fixtures.

The fixtures under test are generated by ``tests/conftest.py`` (session-scoped,
cached under ``tests/.media_cache/``). These tests assert that each generated
file is probeable with the expected duration, that the H.264 sample carries a
forced 2 s closed GOP, and that the SRT sample carries exactly one SubRip
subtitle stream.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from itertools import pairwise
from typing import TYPE_CHECKING, Final

import pytest

if TYPE_CHECKING:
    from collections.abc import Sequence
    from pathlib import Path

pytestmark = pytest.mark.unit

EXPECTED_DURATION: Final[float] = 12.0
DURATION_TOLERANCE: Final[float] = 0.5
GOP_INTERVAL: Final[float] = 2.0
GOP_TOLERANCE: Final[float] = 0.1

ALL_FIXTURES: Final[tuple[str, ...]] = (
    "h264_aac_mp4",
    "hevc_aac_mkv",
    "srt_mkvm",
    "annexb_ts",
    "nonzero_start_ts",
)


def _ffprobe(path: Path, args: Sequence[str]) -> str:
    """Run ffprobe against ``path`` and return its JSON stdout."""
    binary = shutil.which("ffprobe")
    assert binary is not None, "ffprobe not found on PATH"
    proc = subprocess.run(  # noqa: S603 — controlled invocation, no shell
        [binary, "-v", "error", *args, str(path)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, f"ffprobe failed for {path.name}:\n{proc.stderr}"
    return proc.stdout


def _probe_duration(path: Path) -> float:
    """Return the container duration in seconds."""
    data = json.loads(
        _ffprobe(path, ["-show_entries", "format=duration", "-of", "json"])
    )
    return float(data["format"]["duration"])


def _keyframe_gaps(path: Path) -> list[float]:
    """Return the intervals between consecutive keyframe packets (seconds)."""
    data = json.loads(
        _ffprobe(
            path,
            [
                "-select_streams",
                "v:0",
                "-show_packets",
                "-show_entries",
                "packet=pts_time,flags",
                "-of",
                "json",
            ],
        )
    )
    times = [
        float(packet["pts_time"])
        for packet in data["packets"]
        if "K" in packet.get("flags", "")
    ]
    return [end - start for start, end in pairwise(times)]


@pytest.mark.parametrize("fixture_name", ALL_FIXTURES)
def test_duration_matches_expectation(
    fixture_name: str, request: pytest.FixtureRequest
) -> None:
    """Given a generated sample; when probed; then duration is 12.0 ± 0.5 s."""
    sample = request.getfixturevalue(fixture_name)
    assert _probe_duration(sample.path) == pytest.approx(
        EXPECTED_DURATION, abs=DURATION_TOLERANCE
    )


def test_h264_keyframe_interval_is_closed_gop(request: pytest.FixtureRequest) -> None:
    """Given the H.264 sample; when keyframes are inspected; then gaps are 2.0 s."""
    sample = request.getfixturevalue("h264_aac_mp4")
    if sample.codec != "libx264":
        pytest.skip("forced GOP assertion requires libx264")
    gaps = _keyframe_gaps(sample.path)
    assert gaps, "no keyframe gaps found — expected a forced 2 s closed GOP"
    for gap in gaps:
        assert gap == pytest.approx(GOP_INTERVAL, abs=GOP_TOLERANCE)


def test_srt_sample_has_one_subrip_stream(request: pytest.FixtureRequest) -> None:
    """Given the SRT sample; when streams are inspected; then one SubRip subtitle."""
    sample = request.getfixturevalue("srt_mkvm")
    data = json.loads(
        _ffprobe(
            sample.path,
            ["-show_entries", "stream=codec_type,codec_name", "-of", "json"],
        )
    )
    subtitles = [s for s in data["streams"] if s.get("codec_type") == "subtitle"]
    assert len(subtitles) == 1
    # ffmpeg reports SRT/SubRip subtitles in Matroska as codec_name "subrip";
    # accept the "srt" alias for environments that name it differently.
    assert subtitles[0]["codec_name"] in {"srt", "subrip"}
